version: '3.7'

x-custom:
  app:
    - &name "${APP_NAME:-laravel}"
    - &env "${APP_ENV:-local}"
    - &debug "${APP_DEBUG:-true}"
    - &url "${APP_HOST:-http://localhost}"
  db:
    - &db_host "${DB_HOST:-db}"
    - &db_port "${DB_PORT:-3306}"
    - &db_name "${DB_NAME:-laravel}"
    - &db_user "${DB_USER:-laravel}"
    - &db_password "${DB_PASSWORD:-laravel}"
    - &db_root_password "${DB_ROOT_PASSWORD:-root}"
  redis:
    - &redis_host "${REDIS_HOST:-redis}"
    - &redis_port "${REDIS_PORT:-6379}"
    - &redis_password "${REDIS_PASSWORD:-null}"
  port:
    - &database_port "${DATABASE_PORT:-13306:3306}"
    - &app_port "${APP_PORT:-10080:80}"


services:
  app:
    image: "${REGISTRY:-ntsuchiya1105}/laravel:${IMAGE_TAG:-latest}"
    ports:
      - *app_port
    environment:
      WAIT_HOSTS: db:3306, redis:6379
      APP_NAME: *name
      APP_ENV: *env
      APP_DEBUG: *debug
      APP_URL: *url
      DB_HOST: *db_host
      DB_PORT: *db_port
      DB_DATABASE: *db_name
      DB_USERNAME: *db_user
      DB_PASSWORD: *db_password
      REDIS_HOST: *redis_host
      REDIS_PORT: *redis_port
      REDIS_PASSWORD: *redis_password
    volumes:
    - ./app/src:/app
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    ports:
      - *database_port
    environment:
      MYSQL_ROOT_PASSWORD: *db_root_password
      MYSQL_DATABASE: *db_name
      MYSQL_USER: *db_user
      MYSQL_PASSWORD: *db_password
    volumes:
      - db:/var/lib/mysql

  redis:
    image: redis:5-alpine3.11

volumes:
  db:
